version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-baseline
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - TZ=UTC
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs